# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#

use_frameworks!
#source = 'https://ivanjueves@bitbucket.org/ivanjueves/specs.git'
#source = 'https://github.com/CocoaPods/Specs.git'


def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'Today' do

   pod 'FancyButton'  , :git => 'https://ivanjueves@bitbucket.org/ivanjueves/fancybutton.git'
   pod 'Kingfisher', '~> 4.0'
   pod 'Alamofire', '~> 4.7'
   pod 'Hero', '~> 1.1'
   pod 'SwiftyJSON'
   pod 'Alamofire-SwiftyJSON'
   pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4' 
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for Today
end

target 'TodayTests' do
    testing_pods
end
